# Generated by Django 2.2.5 on 2019-09-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('em_website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='test1',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
