# Generated by Django 2.2.5 on 2019-10-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('em_website', '0004_category_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='time_for_preparation',
            field=models.IntegerField(blank=True, help_text='How many minutes will it take?', null=True, verbose_name='Preparation time'),
        ),
    ]
