# Generated by Django 2.2.5 on 2019-11-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('em_website', '0006_auto_20191031_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedrecipe',
            name='user',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
