# Generated by Django 2.2.5 on 2019-11-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('em_website', '0007_auto_20191101_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedrecipe',
            name='slug',
            field=models.SlugField(),
        ),
    ]
