# Generated by Django 2.2.5 on 2019-11-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('em_website', '0008_auto_20191101_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedrecipe',
            name='user',
            field=models.CharField(max_length=100, verbose_name='User'),
        ),
    ]
