# Generated by Django 2.2.5 on 2019-11-07 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('em_website', '0009_auto_20191101_1112'),
        ('em_website', '0005_auto_20191031_0832'),
    ]

    operations = [
    ]
