# Generated by Django 2.2.5 on 2019-11-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('em_website', '0010_merge_20191107_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(help_text='One ingredient per line', verbose_name='Ingredients'),
        ),
    ]
