# Generated by Django 2.2.5 on 2019-11-10 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('em_website', '0011_auto_20191107_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='recipe',
        ),
    ]
